// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvheSdHPt9E0XJjUcbwj0waIChZ2abzfM',
    appId: '1:191947716778:web:8ff16e025f43553708b8d3',
    messagingSenderId: '191947716778',
    projectId: 'news2learn',
    authDomain: 'news2learn.firebaseapp.com',
    storageBucket: 'news2learn.firebasestorage.app',
    measurementId: 'G-WD3R00VZ9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1U0J09UaTJH8Q-TI401AqVQ8do5jvUiE',
    appId: '1:191947716778:android:5496747a3925d2a408b8d3',
    messagingSenderId: '191947716778',
    projectId: 'news2learn',
    storageBucket: 'news2learn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXl9md4iJEQaZMNN5M_boaWBXnCbaa1Xs',
    appId: '1:191947716778:ios:2f3754234b771f9408b8d3',
    messagingSenderId: '191947716778',
    projectId: 'news2learn',
    storageBucket: 'news2learn.firebasestorage.app',
    iosBundleId: 'com.example.news2learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXl9md4iJEQaZMNN5M_boaWBXnCbaa1Xs',
    appId: '1:191947716778:ios:2f3754234b771f9408b8d3',
    messagingSenderId: '191947716778',
    projectId: 'news2learn',
    storageBucket: 'news2learn.firebasestorage.app',
    iosBundleId: 'com.example.news2learn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvheSdHPt9E0XJjUcbwj0waIChZ2abzfM',
    appId: '1:191947716778:web:09bdbd616c02645408b8d3',
    messagingSenderId: '191947716778',
    projectId: 'news2learn',
    authDomain: 'news2learn.firebaseapp.com',
    storageBucket: 'news2learn.firebasestorage.app',
    measurementId: 'G-Y4R084NWY3',
  );
}
